import type { Criterion } from "./cloudflare-ai";

export type ProjectPhase = {
  id: string;
  title: string;
  description: string;
  prompt: string;
  wordCountMin: number;
  wordCountMax: number;
  tips: string[];
  criteria: Criterion[];
  passThreshold: number; // 0–100
};

export type Project = {
  id: string;
  title: string;
  description: string;
  genre: "nonfiction" | "fiction";
  difficulty: "beginner" | "intermediate" | "advanced";
  deliverable: string;
  phases: ProjectPhase[];
};

const _allProjects: Project[] = [
  {
    id: "opinion-column",
    title: "The Opinion Column",
    description: "Write a 500–700 word opinion piece that argues a specific position with evidence, handles the counterargument, and ends with a punch.",
    genre: "nonfiction",
    difficulty: "beginner",
    deliverable: "A 500–700 word opinion column",
    phases: [
      {
        id: "pitch",
        title: "The Pitch",
        description: "Before you write the column, nail the argument. A strong opinion piece starts with a position so clear you could defend it in one sentence.",
        prompt: "In 100–150 words, answer three questions:\n\n1. State your argument in one specific sentence. Not a topic — a position. (Wrong: \"Social media affects mental health.\" Right: \"Instagram's algorithm actively makes teenage girls feel worse about themselves, and the company knows it.\")\n\n2. List 2–3 specific pieces of evidence or reasoning that support your argument. Name real examples, statistics, or cases — not \"studies show\" but the actual study.\n\n3. Name the strongest counterargument against your position and sketch your response to it in 1–2 sentences.",
        wordCountMin: 80,
        wordCountMax: 175,
        tips: [
          "Your argument should be falsifiable — someone should be able to disagree with it.",
          "The best counterargument is the one that would most convince a neutral reader. Don't pick the weakest objection.",
          "Specific beats vague every time. 'Teenagers' is vague. '16-year-old girls in the US' is specific.",
        ],
        criteria: [
          { name: "Argument clarity", description: "The core position is stated in one specific, falsifiable sentence — a stance, not a topic.", weight: 0.40 },
          { name: "Evidence plan", description: "2–3 concrete, specific supporting points are named. Not vague gestures at evidence but actual examples, data, or cases.", weight: 0.35 },
          { name: "Counterargument", description: "The strongest opposing view is identified and a response is sketched — not dismissed but engaged.", weight: 0.25 },
        ],
        passThreshold: 62,
      },
      {
        id: "draft",
        title: "First Draft",
        description: "Write the full column. At this stage, get the argument on paper — complete, structured, and honest. Polish comes in revision.",
        prompt: "Write a 500–700 word opinion column arguing the position you pitched.\n\nYour column must have:\n- An opening that hooks the reader and arrives at your argument within the first 2 paragraphs\n- Evidence and reasoning that build your case in the body\n- At least one counterargument addressed directly (not dismissed — taken seriously then refuted)\n- An ending that doesn't summarize — it drives the point home with a final punch\n\nWrite with authority. Opinion columns don't hedge. If you're not sure you believe it, the reader won't either.",
        wordCountMin: 480,
        wordCountMax: 720,
        tips: [
          "Don't bury the lede. Many writers spend 200 words getting to their point. Say it in paragraph one.",
          "Addressing the counterargument makes you more credible, not less. It shows you've thought about this.",
          "The best opinion endings don't restate the thesis — they extend it into a final implication or image.",
        ],
        criteria: [
          { name: "Argument clarity", description: "The thesis is clear, specific, and stated within the first two paragraphs.", weight: 0.25 },
          { name: "Opening", description: "The opening earns attention and gets to the argument quickly — no lengthy warm-up.", weight: 0.20 },
          { name: "Evidence quality", description: "Evidence is specific and well-used — concrete examples and data, not vague gestures.", weight: 0.25 },
          { name: "Counterargument", description: "A genuine opposing view is engaged with directly and refuted, not dismissed.", weight: 0.15 },
          { name: "Ending", description: "The ending lands — it extends or sharpens the argument rather than restating it.", weight: 0.15 },
        ],
        passThreshold: 65,
      },
      {
        id: "revision",
        title: "Revision",
        description: "The bones are there. Now make it land. Revision is not about fixing typos — it's about tightening the argument and earning the reader's trust.",
        prompt: "Revise your opinion column with these four specific targets:\n\n1. **The opening sentence.** If someone read only the first sentence, would they keep reading? Rewrite it if not.\n\n2. **Cut the weakest paragraph.** Every opinion column has one — a paragraph that doesn't add to the argument, only extends it. Find it and cut it.\n\n3. **Sharpen the counterargument.** Make sure you're taking the best version of the opposing view seriously, not a straw man.\n\n4. **The ending.** It should feel like the last punch in a fight. Cut anything after your best sentence.\n\nSubmit your revised version (500–700 words).",
        wordCountMin: 480,
        wordCountMax: 720,
        tips: [
          "The best first sentence in an opinion piece creates a problem the rest of the piece resolves.",
          "Cutting is not losing — every word you remove makes the ones that stay stronger.",
          "Read the ending out loud. If it doesn't sound like a conclusion, it isn't one yet.",
        ],
        criteria: [
          { name: "Opening strength", description: "The first sentence and first paragraph command attention and arrive at the argument without delay.", weight: 0.25 },
          { name: "Argument specificity", description: "Every claim is backed by something concrete — no vague generalizations remain.", weight: 0.30 },
          { name: "Counterargument quality", description: "The opposing view feels genuinely engaged with — the reader feels it was taken seriously.", weight: 0.20 },
          { name: "Ending impact", description: "The ending drives the argument home with force — it's the last and best punch.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
    ],
  },

  {
    id: "personal-essay",
    title: "The Personal Essay",
    description: "Write a 700–1000 word personal essay grounded in a specific experience, built toward a genuine insight, and closed with a resonant image — not a moral.",
    genre: "nonfiction",
    difficulty: "intermediate",
    deliverable: "A 700–1000 word personal essay",
    phases: [
      {
        id: "proposal",
        title: "The Proposal",
        description: "Map the essay before you write it. The biggest failure in personal essays isn't bad writing — it's not knowing what the essay is about.",
        prompt: "In 150–200 words, answer three questions:\n\n1. **The experience.** What specific moment or period is this essay about? Name it concretely — the place, the year, the event. Not \"my relationship with my father\" but \"the two weeks after my father's accident when I drove him to physical therapy every morning.\"\n\n2. **The insight.** What did you come to understand? Not a theme — a specific realization. Not \"I learned family matters\" but the actual thought you had, and when you had it.\n\n3. **The arc.** Where does the essay open (a scene, an image, a moment) and where does it end (the emotional landing — what the reader feels last)?",
        wordCountMin: 120,
        wordCountMax: 220,
        tips: [
          "If you can't state the insight in one sentence, you don't know it yet. Keep thinking.",
          "The best personal essays start in the middle of something, not at the beginning of a story.",
          "The ending shouldn't be a lesson. It should be an image or moment that carries the feeling.",
        ],
        criteria: [
          { name: "Specific premise", description: "The experience is named with concrete detail — time, place, event — not described as a theme or topic.", weight: 0.35 },
          { name: "Clear insight", description: "The 'so what' is articulated as a specific realization, not a general theme or lesson.", weight: 0.40 },
          { name: "Structure arc", description: "A clear opening moment and ending beat are identified — the essay has a shape.", weight: 0.25 },
        ],
        passThreshold: 62,
      },
      {
        id: "draft",
        title: "First Draft",
        description: "Write the essay. At this stage, completeness matters more than perfection. Get the full arc on the page.",
        prompt: "Write a 700–1000 word personal essay based on your proposal.\n\nStart with a scene — not an explanation. Drop the reader into a moment. Move through the experience using scene (slow down time) and summary (speed through it). Arrive at the insight as something that emerges from what happened, not something you announce.\n\nClose with an image or moment, not a moral. The reader should feel the insight without being told it.\n\nDon't worry about perfect sentences at this stage. Get the full shape on the page.",
        wordCountMin: 680,
        wordCountMax: 1040,
        tips: [
          "Resist the urge to explain what things meant as you describe them. Show the moment, let the meaning come later.",
          "The best personal essays trust the reader to feel things the writer doesn't name.",
          "If your draft ends with 'I learned that...' or 'This taught me...', you need a new ending.",
        ],
        criteria: [
          { name: "Scene opening", description: "The essay opens with a scene, image, or concrete moment — not an explanation, summary, or thesis.", weight: 0.20 },
          { name: "Voice", description: "The writing has a distinct, personal voice — it sounds like a specific human being, not generic prose.", weight: 0.20 },
          { name: "Specificity", description: "Details are concrete and particular — real names, real places, real sensory experience.", weight: 0.25 },
          { name: "Insight", description: "The essay arrives at a genuine, specific insight — not a generic lesson but an actual realization.", weight: 0.20 },
          { name: "Ending", description: "The ending resonates through image or moment rather than summarizing or moralizing.", weight: 0.15 },
        ],
        passThreshold: 65,
      },
      {
        id: "revision",
        title: "Revision",
        description: "The essay exists. Now make it inevitable — the feeling that every word was the only word.",
        prompt: "Revise your personal essay with these four targets:\n\n1. **The opening.** Try cutting the first paragraph entirely. Does it start better without it? Many essays earn their real opening in the second paragraph.\n\n2. **The insight.** Find the moment where you explain the insight rather than let it emerge from the scene. Rewrite that passage so the insight is felt, not stated.\n\n3. **The most abstract paragraph.** Find the paragraph where you make claims about what things meant. Convert it into scene or specific detail.\n\n4. **The ending.** Cut the last sentence. Is the one before it stronger? Often it is.\n\nSubmit your revised version (700–1000 words).",
        wordCountMin: 680,
        wordCountMax: 1040,
        tips: [
          "The 'explanation' paragraphs are usually the ones you wrote when you were figuring out what the essay was about. In revision, you can trust the scenes to do that work.",
          "Abstract language (important, meaningful, real, difficult) is almost always cuttable.",
          "The ending that feels 'too abrupt' to the writer usually feels exactly right to the reader.",
        ],
        criteria: [
          { name: "Opening trust", description: "The opening drops the reader into scene or image without over-explaining what is happening or why it matters.", weight: 0.20 },
          { name: "Insight emergence", description: "The central insight comes from the story — it emerges from scene and experience rather than being announced.", weight: 0.30 },
          { name: "Specificity", description: "Abstract or explanatory language has been replaced with concrete detail, scene, and image.", weight: 0.25 },
          { name: "Ending restraint", description: "The ending closes on a specific moment or image — it resonates rather than summarizes.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
    ],
  },

  {
    id: "explainer",
    title: "The Explainer",
    description: "Write a 400–600 word piece that takes something genuinely complex and makes it clear to a smart reader with zero background knowledge.",
    genre: "nonfiction",
    difficulty: "beginner",
    deliverable: "A 400–600 word explainer",
    phases: [
      {
        id: "setup",
        title: "The Setup",
        description: "Define what you're explaining and who you're explaining it to. The failure mode of most explainers is trying to explain everything. This phase forces you to pick one thing.",
        prompt: "In 100–150 words, answer three questions:\n\n1. **The topic.** Frame it as a specific, answerable question — not the subject, but the question. Not \"inflation\" but \"Why did the price of groceries go up 30% in two years even though the economy is supposedly growing?\"\n\n2. **The reader.** Describe them in one sentence. Who are they, and what do they know already? Assume intelligence but zero specialized knowledge.\n\n3. **The takeaway.** Write the single sentence your reader should be able to say after finishing your explainer. Make it concrete and testable — not \"understand inflation\" but the actual thing they'll know.",
        wordCountMin: 80,
        wordCountMax: 175,
        tips: [
          "Frame the topic as a question that a curious, smart non-expert would actually ask.",
          "Your takeaway sentence is your success criterion. If you can't write it, you don't know what you're explaining yet.",
        ],
        criteria: [
          { name: "Topic specificity", description: "The topic is framed as a specific, answerable question — not a broad subject area.", weight: 0.35 },
          { name: "Reader definition", description: "The intended reader is defined clearly enough to guide vocabulary and assumed knowledge.", weight: 0.30 },
          { name: "Takeaway sentence", description: "The one-sentence takeaway is concrete and testable — it names the actual thing the reader will understand.", weight: 0.35 },
        ],
        passThreshold: 62,
      },
      {
        id: "draft",
        title: "First Draft",
        description: "Explain it. This is harder than it sounds. Most writers think they're explaining when they're actually just describing.",
        prompt: "Write a 400–600 word explainer for the topic and reader you defined.\n\nRequirements:\n- **Open with the question or problem** that creates need-to-know. Don't start with context or history — start with why the reader should care.\n- **Define every term** before or immediately after you use it. Never assume the reader knows jargon.\n- **Use at least one analogy** that connects the concept to something from everyday life. Make it earn its place.\n- **End with the so-what** — why does this matter to the reader? Not to society in the abstract, but to them specifically.\n\nTest your draft: could a smart 16-year-old read this and explain it back to a friend?",
        wordCountMin: 380,
        wordCountMax: 620,
        tips: [
          "The opening question should feel urgent. 'You may have heard of X' is not urgent. 'Here's why your rent keeps going up' is.",
          "Analogies fail when they're more complicated than the thing they're explaining. Keep them simple.",
        ],
        criteria: [
          { name: "Opening hook", description: "Opens with the question or problem that creates need-to-know — not background or context.", weight: 0.20 },
          { name: "Jargon handling", description: "Technical terms are defined immediately when used. No assumed knowledge of specialized vocabulary.", weight: 0.25 },
          { name: "Analogy use", description: "At least one analogy connects the concept to everyday experience and genuinely clarifies rather than decorates.", weight: 0.25 },
          { name: "Reader respect", description: "The explainer is neither condescending nor assumes too much. It treats the reader as smart but uninformed.", weight: 0.15 },
          { name: "So-what ending", description: "The ending explains why this matters to the specific reader — not abstractly to the world.", weight: 0.15 },
        ],
        passThreshold: 65,
      },
      {
        id: "revision",
        title: "Revision",
        description: "Tighten and clarify. The goal: every sentence moves the explanation forward. No sentence should be there just to transition.",
        prompt: "Revise your explainer with these four targets:\n\n1. **Economy.** Read each sentence and ask: does this move the explanation forward, or is it throat-clearing? Cut anything that doesn't earn its place.\n\n2. **The analogy.** Does it actually clarify? Read it fresh. If you had to explain it to someone who didn't know the analogy, would it help? If not, replace it.\n\n3. **The hardest paragraph.** Find the part of your explainer that was hardest to write — that's usually the part the reader will find hardest to understand. Rewrite it from scratch.\n\n4. **The ending.** The reader should finish feeling like they got something useful. Does yours do that?\n\nSubmit your revised version (400–600 words).",
        wordCountMin: 380,
        wordCountMax: 620,
        tips: [
          "If you find yourself writing 'In other words...' your first words didn't do their job. Cut the original and keep the restatement.",
          "The hardest paragraph to write is usually the one that needs the most work in revision.",
        ],
        criteria: [
          { name: "Economy", description: "Every sentence earns its place — no padding, no restating, no throat-clearing transitions.", weight: 0.30 },
          { name: "Analogy quality", description: "The analogy makes the concept clearer than the concept explanation alone — it adds genuine illumination.", weight: 0.30 },
          { name: "Clarity at hardest point", description: "The most technically complex passage is handled clearly enough that a non-expert can follow it.", weight: 0.25 },
          { name: "Ending utility", description: "The reader ends feeling like they gained something specific and useful.", weight: 0.15 },
        ],
        passThreshold: 70,
      },
    ],
  },

  {
    id: "the-profile",
    title: "The Profile",
    description: "Write a 600–1000 word character-driven profile of a real or invented person. By the end, the reader should feel like they've met someone.",
    genre: "nonfiction",
    difficulty: "advanced",
    deliverable: "A 600–1000 word profile",
    phases: [
      {
        id: "pitch",
        title: "The Pitch",
        description: "Before you write about this person, prove they're worth writing about — and prove you know the angle.",
        prompt: "In 150–200 words, answer three questions:\n\n1. **The subject.** Who is this person? Name them and place them in their world — not their job title but what they actually do, and what world they inhabit.\n\n2. **The angle.** Why this person, why now? A profile isn't a biography. It has a specific lens. What is the one aspect of this person — a contradiction, a transformation, an obsession, a way of working — that the piece will explore?\n\n3. **The opening scene.** What specific moment, place, or image opens the profile? Not 'at their desk' but the exact desk, the exact moment. Walk us into it.",
        wordCountMin: 120,
        wordCountMax: 220,
        tips: [
          "The angle is not the person's job. It's the specific thing about this person that makes a profile necessary.",
          "The opening scene should put the subject in motion — doing something, not describing something.",
          "If you can't name the angle, you're not ready to write the profile. Keep thinking.",
        ],
        criteria: [
          { name: "Subject placement", description: "The subject is specific and placed in their actual world — not a job title but a living, particular person.", weight: 0.25 },
          { name: "Angle", description: "There is a clear, specific angle — the particular lens through which this profile will see the subject.", weight: 0.40 },
          { name: "Opening scene", description: "The opening scene is concrete and specific — a particular moment, place, and image, not a general setting.", weight: 0.35 },
        ],
        passThreshold: 65,
      },
      {
        id: "draft",
        title: "First Draft",
        description: "Write the profile. The reader should feel like they've met someone real.",
        prompt: "Write a 600–1000 word profile based on your pitch.\n\nStart with the scene you pitched. Move between scene (present moments with the subject), summary (background that matters), and specific detail (physical, behavioral) to render this person fully.\n\nInclude:\n- At least one moment of physical detail that reveals something about the subject (not their appearance — their being)\n- At least one moment where the subject's character is shown through action or speech, not description\n- At least one passage where the subject speaks — quoted or paraphrased in a way that sounds like them\n\nEnd with an image or moment, not a summary. The reader should close the piece with a feeling about this person.",
        wordCountMin: 580,
        wordCountMax: 1040,
        tips: [
          "The best profile detail is specific enough that no other person in the world could be described that way.",
          "Avoid adjectives that tell the reader what to feel ('fascinating', 'remarkable'). Show the thing that is fascinating.",
          "The subject's voice, even paraphrased, should sound different from the writer's voice.",
        ],
        criteria: [
          { name: "Scene opening", description: "Opens with the specific scene from the pitch — vivid, present, immediate, not described from a distance.", weight: 0.20 },
          { name: "Character rendering", description: "The subject feels like a specific, particular person — not a type, a representative, or a collection of traits.", weight: 0.25 },
          { name: "Physical/behavioral detail", description: "Specific details render the subject through sense or action — not adjectives but observations.", weight: 0.20 },
          { name: "Voice", description: "The subject's voice (direct or paraphrased) sounds like a distinct person, not like the writer.", weight: 0.20 },
          { name: "Structure", description: "The piece has a clear shape — it moves somewhere and arrives somewhere, not just accumulating detail.", weight: 0.15 },
        ],
        passThreshold: 65,
      },
      {
        id: "revision",
        title: "Revision",
        description: "Cut the description. Add the observation. The subject should come alive through what they do, not what they look like.",
        prompt: "Revise your profile with these four targets:\n\n1. **The opening.** Can you start one paragraph later? Often the real opening is buried in paragraph two. Try it.\n\n2. **Show vs. tell.** Find the paragraph where you tell the reader what to think or feel about the subject ('he was intense', 'she radiated confidence'). Rewrite it as a specific observation — what did you see that told you this?\n\n3. **The most generic sentence.** Find it. Make it specific enough that it could only describe this person.\n\n4. **The ending.** It should leave the reader with an image of this person in motion, not a summary of what they represent.\n\nSubmit your revised version (600–1000 words).",
        wordCountMin: 580,
        wordCountMax: 1040,
        tips: [
          "Telling adjectives (brilliant, intense, warm) are almost always cuttable — the observation that prompted them is almost always more powerful.",
          "Generic sentences are sentences that could describe any person in this subject's position. Find those and make them specific to this one.",
        ],
        criteria: [
          { name: "Scene vividness", description: "The opening drops the reader into a specific, sensory, present-tense moment.", weight: 0.25 },
          { name: "Show vs. tell", description: "Character is revealed through specific observation and action — not adjectives or authorial judgment.", weight: 0.30 },
          { name: "Specificity", description: "Generic descriptions have been replaced with particular, observable detail that could only describe this subject.", weight: 0.25 },
          { name: "Ending image", description: "The ending closes on a specific image or moment — the reader's last impression is of the subject in motion.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
    ],
  },

  {
    id: "short-story",
    title: "The Short Story",
    description: "Write a complete short story — 800–1200 words, with a beginning, middle, and end. Something must change.",
    genre: "fiction",
    difficulty: "intermediate",
    deliverable: "A complete 800–1200 word short story",
    phases: [
      {
        id: "blueprint",
        title: "The Blueprint",
        description: "A story needs architecture. You need to know where it ends before you start writing, or you'll write a vignette instead of a story.",
        prompt: "In 150–200 words, answer four questions:\n\n1. **The want.** What does your protagonist want in the immediate scene? Not a life goal — what do they want in the next hour? Make it concrete and specific.\n\n2. **The obstacle.** What stands between them and that want? It should be in direct tension with the want — not just a difficulty but a specific opposition.\n\n3. **The change.** How does the story end? What is different for the protagonist — in their situation, their understanding, or both — at the end vs. the beginning?\n\n4. **The first sentence.** Write the actual first sentence of the story. It should put something in motion.",
        wordCountMin: 120,
        wordCountMax: 220,
        tips: [
          "The want must be something the reader can root for or against. 'Wants to find meaning' is not a story want. 'Wants to get out of the car before her father says one more word' is.",
          "The best first sentences raise a question. Not always explicitly — but they make the reader need to read the second sentence.",
        ],
        criteria: [
          { name: "Protagonist want", description: "The immediate want is specific, concrete, and rootable — a desire in a moment, not a life theme.", weight: 0.30 },
          { name: "Conflict clarity", description: "The obstacle is in direct, clear tension with the want — not a general difficulty but a specific opposition.", weight: 0.30 },
          { name: "Change", description: "There is a clear sense of what is different by the end — something must change, even if small.", weight: 0.25 },
          { name: "First sentence", description: "The proposed first sentence puts something in motion and creates forward momentum.", weight: 0.15 },
        ],
        passThreshold: 62,
      },
      {
        id: "draft",
        title: "First Draft",
        description: "Write the story. Trust your blueprint, but let the story surprise you. The best stories deviate from the plan — as long as something still changes.",
        prompt: "Write a complete short story of 800–1200 words based on your blueprint.\n\nRequirements:\n- A beginning that puts your protagonist in motion and establishes the want\n- A middle that raises the stakes — the obstacle gets harder\n- An ending that resolves the conflict — even if ambiguously\n\nWrite in scene. Show what happens, don't summarize it. Trust the reader to feel what you haven't named. Resist the urge to explain what things mean.\n\nIf dialogue helps, use it — but make it sound like people talking, not like characters exchanging plot information.",
        wordCountMin: 760,
        wordCountMax: 1240,
        tips: [
          "If you're summarizing ('Over the next few days, things got worse'), ask yourself: what's the scene that shows this? Write that instead.",
          "The best short story middles make the reader feel that the protagonist can't win — and also can't give up.",
          "An ambiguous ending is fine. A 'nothing changed' ending is not.",
        ],
        criteria: [
          { name: "Story completeness", description: "The story has a clear beginning, middle, and end — something meaningfully changes for the protagonist.", weight: 0.20 },
          { name: "Scene over summary", description: "Events happen on the page in scene — not summarized from a narrative distance.", weight: 0.20 },
          { name: "Dialogue", description: "Dialogue (if present) sounds like real people with real stakes — not plot delivery or character explanation.", weight: 0.15 },
          { name: "Tension", description: "Something is at stake throughout. The story has no dead weight — every scene earns its place.", weight: 0.20 },
          { name: "Ending", description: "The ending resolves the tension in a way that feels earned — not arbitrary, not explained away.", weight: 0.25 },
        ],
        passThreshold: 65,
      },
      {
        id: "revision",
        title: "Revision",
        description: "Make every sentence fight for its place. In revision, you're not adding — you're clarifying and sharpening what's already there.",
        prompt: "Revise your story with these four targets:\n\n1. **The first sentence.** It has to earn the reader's attention. Is it the best sentence in the piece? It should be.\n\n2. **The longest scene.** Find it. Cut it by a third. You'll be surprised what wasn't necessary.\n\n3. **The expository dialogue.** Find the line where a character explains something to another character who should already know it ('As you know, Bob...'). Rewrite it so the character sounds like they're actually talking.\n\n4. **The ending.** Remove the last paragraph. Read the new ending. Is it stronger? Often it is.\n\nSubmit your revised version (800–1200 words).",
        wordCountMin: 760,
        wordCountMax: 1240,
        tips: [
          "Cutting the last paragraph is a trick that works more often than it should. Writers tend to over-explain their endings.",
          "Expository dialogue is dialogue that exists to inform the reader, not to serve the scene. Characters rarely explain things to each other in real life.",
          "The longest scene in a short story is almost always the one that most needs cutting.",
        ],
        criteria: [
          { name: "First sentence", description: "The first sentence pulls the reader forward — it has energy, specificity, or creates immediate tension.", weight: 0.20 },
          { name: "Economy", description: "The story has no dead weight — every scene, paragraph, and line earns its place.", weight: 0.25 },
          { name: "Dialogue authenticity", description: "Dialogue sounds like people talking — not characters delivering information or explaining backstory.", weight: 0.20 },
          { name: "Tension maintenance", description: "Tension is present throughout — quiet moments feel purposeful, not slack.", weight: 0.15 },
          { name: "Ending strength", description: "The ending delivers — it feels earned, resonant, and not over-explained.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
    ],
  },
  {
    id: "the-review",
    title: "The Review",
    description: "Learn to write criticism with a clear angle — not a summary, not a star rating, but a real argument about what something does and why it matters.",
    genre: "nonfiction",
    difficulty: "beginner",
    deliverable: "A 400–500 word review with a clear argument",
    phases: [
      {
        id: "the-review-phase-1",
        title: "The Angle",
        description: "Before you write a word of the review itself, you need to know what you actually think — and what argument you're making. This phase forces you to find the angle.",
        prompt: "Pick something you've experienced recently: a book, film, restaurant, album, product, show, place. In 100–150 words, answer two questions: What is the thing, and what is your single sharpest claim about it? Not 'it was good' or 'I enjoyed it' — a claim with a edge. 'This cookbook solves the problem every other one ignores.' 'The film mistakes cruelty for depth.' Write it as if you're telling a smart friend who asked for your honest take.",
        wordCountMin: 100,
        wordCountMax: 150,
        tips: [
          "Test your claim: could a reasonable person disagree with it? If not, it's not an argument yet.",
          "Avoid 'it was interesting' or 'it was good' — those are placeholders, not claims.",
          "Your angle doesn't have to be harsh — it just has to be specific. 'Quietly devastating' beats 'really sad.'",
        ],
        criteria: [
          { name: "Single claim", description: "There is one clear, specific argument — not a list of impressions.", weight: 0.40 },
          { name: "Specificity", description: "The subject is named and the claim is particular to it, not generic.", weight: 0.35 },
          { name: "Edge", description: "The claim has a point of view — it takes a position someone could disagree with.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
      {
        id: "the-review-phase-2",
        title: "First Draft",
        description: "Write the review. Lead with your angle, support it with specific evidence from the thing itself, and don't soften your conclusion.",
        prompt: "Write a full review of the subject you chose in Phase 1. Open with your angle — don't bury it. Use at least two specific moments, details, or examples from the thing itself as evidence. End with a clear verdict that follows from your argument. 400–500 words. No score, no star rating, no hedging.",
        wordCountMin: 400,
        wordCountMax: 500,
        tips: [
          "Open with your strongest sentence — the one that contains your argument. Don't build up to it.",
          "Evidence means specific: a quote, a scene, a detail, a moment. Not 'the pacing was off.'",
          "Your job is not to describe the thing — it's to make an argument about it.",
        ],
        criteria: [
          { name: "Angle-led opening", description: "The review opens with or immediately establishes the central claim.", weight: 0.25 },
          { name: "Specific evidence", description: "At least two concrete details from the subject are used to support the argument.", weight: 0.30 },
          { name: "Argument coherence", description: "Each paragraph advances the argument — no filler, no pure summary.", weight: 0.25 },
          { name: "Verdict", description: "The ending delivers a clear, earned conclusion.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
      {
        id: "the-review-phase-3",
        title: "Revision",
        description: "Sharpen the argument and cut everything that doesn't earn its place.",
        prompt: "Revise your review. Cut any paragraph that summarizes without arguing. Sharpen every sentence that hedges or softens. Make sure your opening line could stand alone as the piece's thesis. Target: 350–450 words. The revision should feel more confident and more specific than the draft — not shorter for its own sake, but tighter because every sentence is doing work.",
        wordCountMin: 350,
        wordCountMax: 450,
        tips: [
          "Read each paragraph and ask: is this arguing or is this summarizing? Cut anything that only summarizes.",
          "Find every hedge: 'somewhat,' 'in some ways,' 'might.' Either commit to the claim or cut it.",
          "Your last sentence should feel conclusive — a verdict, not a trailing thought.",
        ],
        criteria: [
          { name: "Argument sharpness", description: "The central claim is clearer and more specific than in the draft.", weight: 0.30 },
          { name: "Cut discipline", description: "Summary and hedging have been cut; what remains is argument and evidence.", weight: 0.30 },
          { name: "Opening line", description: "The first sentence carries the piece's argument or hooks the reader with a specific claim.", weight: 0.20 },
          { name: "Verdict strength", description: "The ending is more decisive than the draft version.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
    ],
  },
  {
    id: "flash-fiction",
    title: "Flash Fiction",
    description: "Write a complete story in under 500 words. Flash fiction is the hardest discipline in fiction — every sentence must carry weight. Learn to compress without losing the thing that makes a story a story.",
    genre: "fiction",
    difficulty: "beginner",
    deliverable: "A complete flash fiction story, 400–500 words",
    phases: [
      {
        id: "flash-fiction-phase-1",
        title: "Blueprint",
        description: "A flash piece can't carry backstory or setup. You need to know your three things before you write a word: who wants what, what's in the way, and where it turns.",
        prompt: "In 100–150 words, answer these three questions about your flash piece: (1) Who is this about and what do they want — right now, in this moment? (2) What is blocking them — not a life circumstance, but what's actually in the way in this scene? (3) Where does it turn — what changes, even slightly, by the end? Don't write the story yet. Write the engine.",
        wordCountMin: 100,
        wordCountMax: 150,
        tips: [
          "The want should be immediate — something they need right now, not something they want from life in general.",
          "The obstacle should be specific enough to put in one sentence.",
          "The turn doesn't have to be huge — a realization, a decision, a moment of seeing something clearly.",
        ],
        criteria: [
          { name: "Concrete character", description: "The character is specific — not 'a woman' but someone with a particular want.", weight: 0.30 },
          { name: "Immediate obstacle", description: "The obstacle is present-tense and scene-level, not backstory.", weight: 0.35 },
          { name: "Turn identified", description: "There is a clear moment of change, however small.", weight: 0.35 },
        ],
        passThreshold: 70,
      },
      {
        id: "flash-fiction-phase-2",
        title: "First Draft",
        description: "Write the story. Start in the middle of something. End before you're done explaining.",
        prompt: "Write the flash fiction piece you blueprinted. Start in action or mid-moment — no setup, no 'it was a Tuesday.' End one beat after the turn, without explaining what it means. 400–500 words. Every sentence must be doing something: moving the scene, revealing character, or delivering the turn.",
        wordCountMin: 400,
        wordCountMax: 500,
        tips: [
          "Your first sentence should drop us into the middle of something already happening.",
          "If you find yourself explaining who a character is, cut it and show it through action instead.",
          "When in doubt, cut the last paragraph. Stories almost always end too late.",
        ],
        criteria: [
          { name: "In medias res opening", description: "The story opens in action or in the middle of something — no setup.", weight: 0.20 },
          { name: "Scene compression", description: "The story stays in one tight scene or moment — no time jumps, no backstory dumps.", weight: 0.25 },
          { name: "Turn delivery", description: "The turn from Phase 1 lands clearly in the story.", weight: 0.30 },
          { name: "Ending restraint", description: "The story ends without over-explaining — the reader is trusted.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
      {
        id: "flash-fiction-phase-3",
        title: "Revision",
        description: "Cut the first paragraph. Cut the last sentence. See what survives.",
        prompt: "Revise your flash piece with two rules: (1) Cut the first paragraph — start where the story actually begins. (2) Cut the last sentence — end one beat earlier. Then do a line pass: remove any sentence that explains what a previous sentence already showed. Target: 350–450 words. The story should feel tighter and more compressed — the reader should have to do a little more work, and it should feel better for it.",
        wordCountMin: 350,
        wordCountMax: 450,
        tips: [
          "Read aloud — flash fiction lives or dies by rhythm. Every slow sentence is a problem.",
          "Look for any sentence that explains what the previous sentence already showed. Those go first.",
          "If cutting the first paragraph means starting mid-sentence of the old second paragraph, do it.",
        ],
        criteria: [
          { name: "Compressed opening", description: "The revised opening drops in faster than the draft — less setup, more story.", weight: 0.25 },
          { name: "Restrained ending", description: "The ending trusts the reader — it stops before explaining.", weight: 0.25 },
          { name: "Line-level cut discipline", description: "Explanatory sentences have been removed; showing does the work.", weight: 0.30 },
          { name: "Story completeness", description: "Despite cuts, the story still has a character, an obstacle, and a turn.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
    ],
  },
  {
    id: "feature-lead",
    title: "The Feature Lead",
    description: "The opening of a feature article is the hardest sentence in journalism to write. Learn to open with a scene, stick the landing with a nut graf, and carry the reader from concrete detail to the reason it matters.",
    genre: "nonfiction",
    difficulty: "intermediate",
    deliverable: "A 300–400 word feature opening: scene, nut graf, and follow-through",
    phases: [
      {
        id: "feature-lead-phase-1",
        title: "The Scene",
        description: "Feature leads don't open with the argument — they open with a moment. Before you can write the lead, you need a scene worth opening with, and a clear nut graf that tells the reader why they should care.",
        prompt: "Think of a subject you could write a feature about: a person, a place, a trend, a problem, a change. In 150–200 words, do two things: (1) Write a 3–5 sentence opening scene — a specific moment, in a specific place, with specific sensory detail. Not a summary of the subject. A moment. (2) Write a 2–3 sentence nut graf that follows the scene — what's really going on, why it matters, what the piece will reveal. The nut graf should feel like a landing after the scene's flight.",
        wordCountMin: 150,
        wordCountMax: 200,
        tips: [
          "Your scene should be specific enough that you could draw a picture of it. If not, it's still a summary.",
          "The nut graf answers 'so what?' — after the scene, why does the reader need to keep going?",
          "Scene and nut graf should feel like cause and effect — the scene makes the nut graf inevitable.",
        ],
        criteria: [
          { name: "Scene specificity", description: "The scene is a moment — specific person, place, action, detail.", weight: 0.35 },
          { name: "Nut graf clarity", description: "The nut graf states the subject and its stakes clearly.", weight: 0.35 },
          { name: "Scene-to-nut transition", description: "The nut graf lands naturally from the scene — the connection is felt.", weight: 0.30 },
        ],
        passThreshold: 70,
      },
      {
        id: "feature-lead-phase-2",
        title: "First Draft",
        description: "Write the full opening of the feature — scene, nut graf, and the first section that delivers on the promise.",
        prompt: "Write the opening of your feature: the scene, the nut graf, and a section that begins delivering on the nut graf's promise (at least one more paragraph after the nut graf). 300–400 words total. The scene should feel alive. The nut graf should feel earned. The section that follows should feel like the beginning of an answer to the question your nut graf raised.",
        wordCountMin: 300,
        wordCountMax: 400,
        tips: [
          "The best feature leads feel like you stumbled into a moment — not like a reporter setting up a story.",
          "Your nut graf should name the subject, the stakes, and the revelation. Three sentences maximum.",
          "After the nut graf, start delivering — facts, context, a second scene. Don't tease.",
        ],
        criteria: [
          { name: "Scene quality", description: "The opening scene has specific detail — a reader can picture it.", weight: 0.25 },
          { name: "Nut graf precision", description: "The nut graf tells us exactly what this piece is about and why it matters.", weight: 0.25 },
          { name: "Follow-through", description: "The paragraphs after the nut graf begin answering the question it raised.", weight: 0.25 },
          { name: "Momentum", description: "The reader is pulled forward — each section earns the next.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
      {
        id: "feature-lead-phase-3",
        title: "Revision",
        description: "Tighten the scene and sharpen the nut graf until the opening is airtight.",
        prompt: "Revise your feature opening. Tighten the scene: cut any sentence that tells the reader what to think about what they're seeing. Sharpen the nut graf: it should be 2 sentences maximum — the subject, and the stake. Review the section that follows: does every paragraph advance or does any just add more? Target: 280–380 words. The revision should feel more urgent and more focused than the draft.",
        wordCountMin: 280,
        wordCountMax: 380,
        tips: [
          "If your scene contains any sentence that tells the reader what to think, that sentence comes out.",
          "Read your nut graf out loud. If it sounds like a press release, it needs another pass.",
          "Every paragraph after the nut graf should answer a question the nut graf raised. If it doesn't, cut it.",
        ],
        criteria: [
          { name: "Scene purity", description: "The scene shows without telling — no sentences that explain the scene's meaning.", weight: 0.30 },
          { name: "Nut graf tightness", description: "The nut graf is 2 sentences or fewer and says exactly what it needs to say.", weight: 0.30 },
          { name: "Section discipline", description: "Every paragraph after the nut graf is pulling weight.", weight: 0.20 },
          { name: "Urgency", description: "The revised opening moves faster and feels more purposeful than the draft.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
    ],
  },
  {
    id: "publish-it",
    title: "Publish It",
    description: "Take a piece from idea to actual submission. Four phases: find the angle, write the draft, revise it, then pitch it to a real editor at a real publication. The goal isn't a finished document — it's a sent email.",
    genre: "nonfiction",
    difficulty: "intermediate",
    deliverable: "A revised 500–800 word piece and a real pitch email to an editor",
    phases: [
      {
        id: "publish-it-phase-1",
        title: "The Angle",
        description: "Before you write a word, you need to know what the piece is and where it lives. Not just the topic — the specific angle, the publication, and why you're the person to write it.",
        prompt: "In 100–150 words, answer four questions: (1) What is the piece — not the topic, but the specific angle or argument. One sentence. (2) What kind of piece is it — personal essay, op-ed, reported piece, humor, criticism? (3) Name a specific publication where this piece belongs and explain in one sentence why it fits there. (4) Why are you the person to write this? What do you know, have experienced, or have access to that someone else doesn't?",
        wordCountMin: 100,
        wordCountMax: 150,
        tips: [
          "Name an actual publication — not 'a magazine' but The Atlantic, Eater, your local alt-weekly, a specific Substack. The more specific, the better your piece will be.",
          "The angle is not the topic. 'Remote work' is a topic. 'Remote work made me realize I'd been hiding from my own life' is an angle.",
          "Your qualification doesn't have to be a credential. Living through something counts. Caring enough to research it counts.",
        ],
        criteria: [
          { name: "Specific angle", description: "There is one clear, arguable claim — not a topic or a theme.", weight: 0.35 },
          { name: "Publication fit", description: "A real publication is named and the fit is explained specifically.", weight: 0.30 },
          { name: "Writer's authority", description: "There is a clear reason why this writer should be the one to write this piece.", weight: 0.35 },
        ],
        passThreshold: 70,
      },
      {
        id: "publish-it-phase-2",
        title: "First Draft",
        description: "Write the piece. Use the angle from Phase 1. Don't write toward the publication yet — just write the piece as well as you can.",
        prompt: "Write the full piece — personal essay, op-ed, criticism, reported piece, whatever form you chose. Open with your strongest moment or your sharpest sentence, not with setup. End before you've said everything. 500–800 words. Don't edit as you go. Get it down.",
        wordCountMin: 500,
        wordCountMax: 800,
        tips: [
          "Start with the moment, the argument, or the scene — not with background. You can add context later.",
          "The first draft's job is to exist. Perfection is for Phase 3.",
          "If you get stuck, skip to the part you know best and come back.",
        ],
        criteria: [
          { name: "Angle present", description: "The piece's central argument or angle is clearly present.", weight: 0.25 },
          { name: "Strong opening", description: "The piece opens with something that earns the reader's attention immediately.", weight: 0.25 },
          { name: "Completeness", description: "The piece has a beginning, middle, and end — it arrives somewhere.", weight: 0.25 },
          { name: "Specific detail", description: "The piece uses concrete, specific detail rather than generalizations.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
      {
        id: "publish-it-phase-3",
        title: "Revision",
        description: "Now edit with the publication in mind. Read a few recent pieces from your target publication before you revise. Match the register. Cut what doesn't belong.",
        prompt: "Revise your draft for the specific publication you named in Phase 1. Do three things: (1) Cut the first paragraph — start where the piece actually begins. (2) Remove every sentence that doesn't advance the argument or deepen the reader's understanding. (3) Make the ending land — it should feel like a conclusion, not a trailing off. Target: 450–750 words. The revision should feel tighter and more intentional than the draft.",
        wordCountMin: 450,
        wordCountMax: 750,
        tips: [
          "Read two or three recent pieces from your target publication before you revise. Notice the register, the sentence length, the level of directness.",
          "Cut the first paragraph. Seriously. Just try it.",
          "Your last line is your most important. It's what the reader carries away.",
        ],
        criteria: [
          { name: "Tighter opening", description: "The revised piece drops in faster than the draft.", weight: 0.25 },
          { name: "Publication fit", description: "The tone, register, and length feel appropriate for the named publication.", weight: 0.25 },
          { name: "Cut discipline", description: "The revision is leaner — sentences that didn't earn their place are gone.", weight: 0.25 },
          { name: "Ending", description: "The piece ends with purpose — the final line earns its position.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
      {
        id: "publish-it-phase-4",
        title: "The Pitch",
        description: "Write the actual email you will send to an editor. Not a hypothetical. The real one. This is the phase most writers skip — and why most pieces never get published.",
        prompt: "Write a pitch email to an editor at the publication you named. 150–200 words. Structure it like this: (1) One sentence naming the piece and its angle. (2) Two to three sentences on why it belongs in this publication — reference something specific they've published recently. (3) One to two sentences on why you're the right person to write it. (4) A short excerpt or your best sentence from the piece. End with your name and any relevant credentials or links. Write it as if you're going to send it. Because you should.",
        wordCountMin: 150,
        wordCountMax: 200,
        tips: [
          "Find the actual editor's name. Submissions addressed to 'Dear Editor' go to the bottom of the pile.",
          "Reference something specific the publication has run recently — it proves you read them.",
          "Don't summarize the piece at length. Give them the angle and one great sentence. Make them want to read it.",
          "The last line of a pitch is always a version of: 'Happy to send the full piece.' Keep it simple.",
        ],
        criteria: [
          { name: "Clear pitch", description: "The angle is stated in the first sentence — no buildup, no preamble.", weight: 0.30 },
          { name: "Publication knowledge", description: "The pitch references the specific publication with evidence of having actually read it.", weight: 0.25 },
          { name: "Writer's case", description: "There is a clear, specific reason why this writer should write this piece.", weight: 0.25 },
          { name: "Professionalism", description: "The email is concise, direct, and sounds like a writer who respects the editor's time.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
    ],
  },
  {
    id: "long-essay",
    title: "The Long Essay",
    description: "Write a complete 1,500–2,500 word essay from plan to revised draft. The length where structure becomes load-bearing — you can't wing it across 2,000 words the way you can across 600.",
    genre: "nonfiction",
    difficulty: "intermediate",
    deliverable: "A revised 1,500–2,500 word longform essay",
    phases: [
      {
        id: "plan",
        title: "The Plan",
        description: "Before you write 2,000 words, know what they're for. A plan isn't an outline — it's a map of the argument's moves.",
        prompt: "Plan your essay in 150–250 words. Answer five questions:\n\n1. What is the central claim? One sentence. Arguable, specific, yours.\n2. What is the opening scene or moment? Not the topic — the specific entry point. Who, where, when.\n3. What are the 3–4 main moves? Not headers — what does each section do for the argument?\n4. Where is the turn? Every strong long essay has a moment where the argument complicates, deepens, or reverses. Name it.\n5. What is the last line or final image? You don't have to keep it. But having a target stops you from drifting.",
        wordCountMin: 130,
        wordCountMax: 270,
        tips: [
          "The central claim should be falsifiable. If no one could disagree, it's an observation, not an argument.",
          "The turn is the most important structural element in a long essay. If you don't know where it is before you write, you may not find it at all.",
          "Your opening scene doesn't have to be dramatic. It has to be specific. One sharp detail does more than a paragraph of throat-clearing.",
        ],
        criteria: [
          { name: "Central claim", description: "One specific, arguable sentence — a claim, not a topic.", weight: 0.30 },
          { name: "Specific opening", description: "The entry point is named with concrete detail — not 'I'll open with a scene' but the actual scene.", weight: 0.25 },
          { name: "Structural map", description: "3–4 moves are identified, each named by what it does for the argument.", weight: 0.25 },
          { name: "Turn identified", description: "The essay's turning point is named and located.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
      {
        id: "draft",
        title: "First Draft",
        description: "Write the full essay. This is the longest single piece in the gym so far. Don't make it perfect. Make it complete.",
        prompt: "Write the full essay. 1,500–2,500 words. Work from your plan, but let it breathe.\n\nYour draft must:\n- Open with the specific scene or moment you named in the plan\n- State the central claim clearly by the end of the first page\n- Include at least two extended scenes or case studies (not just references — developed examples)\n- Include the turn\n- Arrive somewhere by the end\n\nDon't edit as you go. The first draft's job is to exist.",
        wordCountMin: 1500,
        wordCountMax: 2500,
        tips: [
          "If you get stuck, skip to the section you know best. Come back to the gap later.",
          "Your extended examples should be specific enough to be scenes. Name the person. Name the place. Name what happened.",
          "The turn often comes two-thirds of the way through. It's the moment you complicate your own argument or admit what the simple version misses.",
        ],
        criteria: [
          { name: "Scene opening", description: "The essay opens with a specific scene or moment — not background, not thesis, not 'in this essay.'", weight: 0.20 },
          { name: "Argument visible", description: "The central claim is clear by the end of the first page.", weight: 0.25 },
          { name: "Extended examples", description: "At least two examples are developed at length — not just named but rendered.", weight: 0.25 },
          { name: "Turn present", description: "The argument complicates, deepens, or reverses at some point in the essay.", weight: 0.15 },
          { name: "Arrives somewhere", description: "The essay ends — it doesn't just stop. Something has been established by the final paragraph.", weight: 0.15 },
        ],
        passThreshold: 68,
      },
      {
        id: "revision",
        title: "Revision",
        description: "Revise for structure and voice. At 2,000 words the through-line can drift and the reader can lose the argument. Your job is to make it impossible to lose.",
        prompt: "Revise your essay. Target: 1,400–2,300 words. Work through three things in order:\n\n1. The opening 200 words: cut anything that isn't earning its place. Try deleting the first paragraph entirely — does the essay improve? Often yes.\n2. The through-line: find the 2–3 sentences where you state or restate your central argument. Are they doing work, or are they throat-clearing? Sharpen them.\n3. The ending: read the last paragraph out loud. Then cut the last sentence. Is the sentence before it a better ending? Try it both ways.\n\nThe revision should be tighter and more intentional than the draft.",
        wordCountMin: 1400,
        wordCountMax: 2300,
        tips: [
          "Cut the first paragraph. Seriously. Just try it.",
          "The through-line check: a reader who skims should still be able to follow your argument from the key sentences alone.",
          "Your ending lands when it feels inevitable. If it feels like you ran out of things to say, it doesn't land yet.",
        ],
        criteria: [
          { name: "Tighter opening", description: "The revised essay drops in faster — no unnecessary setup before the argument begins.", weight: 0.25 },
          { name: "Through-line clear", description: "The central argument stays visible throughout — a skimming reader wouldn't lose it.", weight: 0.30 },
          { name: "Ending lands", description: "The final paragraph arrives with purpose — it feels earned, not trailed off.", weight: 0.25 },
          { name: "Voice consistent", description: "The revision sounds like one writer throughout — no gear shifts in register or tone.", weight: 0.20 },
        ],
        passThreshold: 70,
      },
    ],
  },
  {
    id: "the-chapter",
    title: "The Chapter",
    description: "Write a complete book chapter from architecture to revised draft. At 3,000–4,500 words, structure becomes load-bearing in a way it never is in shorter work. This is the closest thing in the gym to writing a book.",
    genre: "nonfiction",
    difficulty: "advanced",
    deliverable: "A complete revised book chapter, 3,000–4,500 words",
    phases: [
      {
        id: "architecture",
        title: "Chapter Architecture",
        description: "A book chapter is too long to improvise. Design it before you write it — not as a rigid outline but as a map of the argument's moves.",
        prompt: "Design your chapter in 200–350 words. Answer five questions:\n\n1. What is the chapter's central argument? One sentence. Not what it covers — what it claims.\n2. What is the opening scene? Be specific: who, where, when. You should be able to close your eyes and see it.\n3. Map the chapter's structure in 5–8 beats. A beat is a unit of the argument — a scene, an analysis, a pivot, a complication. Name what each beat does, not just what it contains.\n4. Where is the chapter's turn — the moment where the argument complicates, deepens, or reverses?\n5. How does this chapter set up the next one? What question does it leave open?",
        wordCountMin: 180,
        wordCountMax: 370,
        tips: [
          "The difference between a beat that 'covers' something and one that 'does' something: 'covers the history of X' vs. 'establishes that the problem predates everyone who claims to have caused it.'",
          "Your opening scene should be the most interesting scene you have. Put your best material up front.",
          "The forward hook at the end isn't a cliffhanger — it's a question the reader didn't know they had until you raised it.",
        ],
        criteria: [
          { name: "Single arguable claim", description: "The chapter's argument is one specific sentence — a claim, not a topic summary.", weight: 0.25 },
          { name: "Specific opening scene", description: "The opening scene is named with concrete detail — not 'a scene about X' but the actual scene.", weight: 0.20 },
          { name: "Beats mapped by function", description: "5+ beats are identified, each described by what it does for the argument.", weight: 0.30 },
          { name: "Turn identified", description: "The chapter's turning point is named and placed.", weight: 0.15 },
          { name: "Forward hook", description: "The question or tension that carries the reader into the next chapter is named.", weight: 0.10 },
        ],
        passThreshold: 70,
      },
      {
        id: "draft",
        title: "First Draft",
        description: "Write the full chapter. This is the longest piece in the gym. Don't try to make it perfect. Make it complete — a beginning, a middle, a turn, and an end.",
        prompt: "Write the full chapter. 3,000–4,500 words.\n\nYour chapter must:\n- Open with a scene before any argument is stated\n- State its central claim clearly by the second or third page\n- Have at least three distinct beats or sections\n- Include at least two extended scenes or case studies — not references, developed examples\n- Have a structural turn where the argument deepens or complicates\n- End with forward momentum: a question, a tension, a hook into what comes next\n\nThis is the longest thing you've written in this gym. Don't edit as you go. Make it exist.",
        wordCountMin: 3000,
        wordCountMax: 4500,
        tips: [
          "Open with your best scene, not your most chronologically logical one.",
          "At 3,000+ words, readers can lose the argument. Restate it — clearly, without apology — somewhere in the middle.",
          "Extended examples at this length should feel like they have their own arc: setup, development, payoff.",
          "The turn is where the chapter earns its length. Everything before it is setup. Everything after it is consequence.",
        ],
        criteria: [
          { name: "Scene opening", description: "The chapter opens with a scene before any argument is stated.", weight: 0.15 },
          { name: "Argument stated", description: "The central claim is clear by the second or third page.", weight: 0.20 },
          { name: "Three distinct beats", description: "The chapter has at least three identifiable sections that each do different work.", weight: 0.20 },
          { name: "Extended scenes", description: "At least two examples are developed at length — rendered, not just referenced.", weight: 0.20 },
          { name: "Turn present", description: "The argument complicates, deepens, or reverses at some point in the chapter.", weight: 0.15 },
          { name: "Forward momentum", description: "The chapter ends with a question or tension that pulls the reader forward.", weight: 0.10 },
        ],
        passThreshold: 65,
      },
      {
        id: "revision",
        title: "Revision",
        description: "Revise with chapter-level priorities. At 4,000 words, small structural problems become large ones. The opening, the transitions, the turn, and the ending each need a separate pass.",
        prompt: "Revise your chapter. Target: 2,800–4,200 words. Work through four things in order:\n\n1. The opening 500 words: cut anything that isn't earning its place. Cut the first paragraph and see if you lose anything real. Usually you don't.\n2. Transitions: find every place where you shift between scenes, time periods, or arguments. Does each transition work? Is it over-explained? Try cutting it to three words or fewer.\n3. The turn: does it land? It should feel like the emotional and argumentative center of the chapter. If it doesn't, find it — it may be buried in the middle of a paragraph.\n4. The ending: read the last paragraph out loud. It should create forward momentum — a question, a tension, a pull toward what comes next. If it feels like a summary, cut it.",
        wordCountMin: 2800,
        wordCountMax: 4200,
        tips: [
          "Transitions that over-explain ('Having established X, we now turn to Y') are usually doing work that the writing itself should do. Cut them.",
          "The turn check: if you removed the turn, would the chapter feel complete? It shouldn't. The turn is what the chapter is building toward.",
          "Read the last paragraph. Cut the last sentence. Is the chapter better? Try it.",
        ],
        criteria: [
          { name: "Opening tighter", description: "The revised chapter drops in faster — the reader is in the argument before the first page ends.", weight: 0.25 },
          { name: "Transitions leaner", description: "Transitions between beats are economical — they don't over-explain the move.", weight: 0.20 },
          { name: "Turn lands", description: "The chapter's turning point is clearly the emotional and argumentative center.", weight: 0.25 },
          { name: "Ending creates forward momentum", description: "The final paragraph leaves a question or tension open — it doesn't summarize.", weight: 0.20 },
          { name: "Chapter arc visible", description: "The chapter has a clear shape: setup, development, turn, consequence.", weight: 0.10 },
        ],
        passThreshold: 68,
      },
    ],
  },
  {
    id: "book-proposal",
    title: "The Book Proposal",
    description: "Write a complete nonfiction book proposal — the document that gets you a deal before the book is written. Agents buy nonfiction on proposal. This is how the industry works.",
    genre: "nonfiction",
    difficulty: "advanced",
    deliverable: "A complete book proposal: hook, market analysis, author platform, chapter outline, and sample chapter",
    phases: [
      {
        id: "hook",
        title: "The Hook",
        description: "One paragraph that answers the only question an agent has time to ask: what is this book and why does it need to exist? Most proposals fail here.",
        prompt: "Write the overview paragraph for your book proposal. 100–150 words. Answer four questions in this order:\n\n1. What is the book? Name the subject and your central argument or premise in one sentence.\n2. What does the reader get? What will they know, feel, or be able to do after reading it that they can't now?\n3. Why now? What makes this book urgent or timely?\n4. What is it like? Give one comp title and one sentence on how yours differs.\n\nDo not start with a question. Do not use the words 'journey' or 'explore.' Be specific. Every sentence must earn its place.",
        wordCountMin: 90,
        wordCountMax: 175,
        tips: [
          "The book's premise should be arguable — someone should be able to disagree with your central claim.",
          "Name a specific reader. Not 'anyone interested in X' but 'readers who loved [comp title]' or 'people who have experienced X.'",
          "The 'why now' doesn't have to be a news hook. It can be a cultural shift, a gap in the conversation, or a moment when the question your book answers has become unavoidable.",
        ],
        criteria: [
          { name: "Clear premise", description: "The book's central argument or premise is stated in one specific sentence — not a topic but a claim.", weight: 0.35 },
          { name: "Reader promise", description: "It's clear what the reader gains — what they'll know, feel, or be able to do after reading.", weight: 0.30 },
          { name: "Urgency", description: "There is a reason why this book needs to exist now, not in five years.", weight: 0.20 },
          { name: "Specificity", description: "No vague language — the paragraph names real things, real readers, real comparisons.", weight: 0.15 },
        ],
        passThreshold: 72,
      },
      {
        id: "market",
        title: "Comps & Market",
        description: "Show you know where your book lives. Agents use comps to assess commercial potential. Pick wrong and you lose them immediately.",
        prompt: "Write the market and comparable titles section of your proposal. 200–300 words.\n\nFirst, name the primary audience in two sentences. Be specific: demographics, what else they read, where they gather.\n\nThen list 3–5 comparable titles published in the last five years. For each, give: title, author, one sentence on what it does, one sentence on how yours is different. Don't pick bestsellers from 15 years ago. Don't pick books that are too similar (it implies no room) or too different (it implies you don't know the shelf).\n\nEnd with one sentence on market size or trend if you have a real data point.",
        wordCountMin: 180,
        wordCountMax: 320,
        tips: [
          "Comps should be published in the last 3–5 years. Older than that and agents assume you don't read current books in your category.",
          "The sweet spot: books similar enough that an agent sees the shelf, different enough that yours has a reason to exist.",
          "Don't comp to mega-bestsellers like Sapiens or Atomic Habits. It reads as naive. Find the mid-list books in your lane.",
          "Your audience section should be specific enough that an agent can picture the reader. 'General readers' is not an audience.",
        ],
        criteria: [
          { name: "Audience specificity", description: "The target reader is described specifically — not 'anyone' but a defined person or community.", weight: 0.25 },
          { name: "Comp recency", description: "All comparable titles cited were published in the last five years.", weight: 0.20 },
          { name: "Comp accuracy", description: "The comps are genuinely similar in subject, tone, or audience — not random bestsellers.", weight: 0.30 },
          { name: "Differentiation", description: "For each comp, it's clear what your book does that the comp doesn't.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
      {
        id: "author-platform",
        title: "Author Platform",
        description: "Why you? Nonfiction is sold on the author as much as the idea. Your platform — audience, credentials, access — is a commercial argument.",
        prompt: "Write the author bio and platform section of your proposal. 150–200 words. Answer three things:\n\n1. What gives you the authority to write this book? This can be professional credentials, lived experience, years of research, or exclusive access. Be specific.\n2. What is your platform? List newsletter subscribers, social following, podcast listeners, speaking engagements — real numbers. If the numbers are small, name the quality of the audience instead.\n3. Why are you the right person — not just a qualified person, but the right one — to write this particular book?\n\nWrite in third person, as it will appear in the proposal.",
        wordCountMin: 130,
        wordCountMax: 220,
        tips: [
          "Real numbers beat vague claims. '4,200 newsletter subscribers' is better than 'an engaged online following.'",
          "Lived experience counts as authority. If the book is about surviving something, say that directly.",
          "If your platform is small, focus on access: relationships with sources, institutions, or communities that give your research credibility.",
          "Write in third person. Proposals are business documents, not cover letters.",
        ],
        criteria: [
          { name: "Authority", description: "There is a clear, specific reason why this writer has the standing to write this book.", weight: 0.40 },
          { name: "Platform evidence", description: "Real numbers or specific evidence of an audience are provided — not vague gestures.", weight: 0.35 },
          { name: "Right person argument", description: "It's clear why this writer specifically — not just someone with their credentials — should write this book.", weight: 0.25 },
        ],
        passThreshold: 70,
      },
      {
        id: "chapter-outline",
        title: "Chapter Outline",
        description: "Map the entire book. Most proposals fail here — writers describe what each chapter 'covers' without showing what each chapter argues. Cover is a topic. Argue is a chapter.",
        prompt: "Write the chapter-by-chapter outline for your book. One paragraph per chapter (2–4 sentences each). Total: 400–600 words.\n\nFor each chapter, state:\n1. The chapter's central argument or revelation — what does the reader believe after this chapter that they didn't before?\n2. The key material — what story, case, data, or scene carries the argument?\n3. How it advances the book — what does this chapter do that the previous one couldn't?\n\nInclude an Introduction that sets up the book's promise. Aim for 6–10 chapters. Do not just describe topics — show the argument progressing.",
        wordCountMin: 380,
        wordCountMax: 640,
        tips: [
          "Each chapter should change the reader in some way — a new belief, a new frame, a new question. If a chapter just 'covers' a topic, it's doing too little.",
          "The outline should have a through-line. By the end, the reader should have arrived somewhere they couldn't have gotten without reading the whole book.",
          "Name the specific story or case study in each chapter. Not 'we look at a company that failed' but 'the 2019 collapse of WeWork illustrates...'",
          "Vary the chapter types: some argue, some illustrate, some complicate, some resolve. A book that only argues is exhausting.",
        ],
        criteria: [
          { name: "Chapter arguments", description: "Each chapter has a clear argument or revelation — not just a topic.", weight: 0.35 },
          { name: "Progression", description: "The chapters build on each other — each one does something the previous one couldn't.", weight: 0.30 },
          { name: "Specific material", description: "Key stories, cases, or scenes are named — the outline shows the actual substance of the book.", weight: 0.20 },
          { name: "Completeness", description: "The outline covers the whole book from introduction to conclusion.", weight: 0.15 },
        ],
        passThreshold: 70,
      },
      {
        id: "sample-chapter",
        title: "Sample Chapter",
        description: "This is the proof. Everything else in the proposal argues that you can write the book. This is you writing it. One bad sample chapter sinks a proposal that everything else built.",
        prompt: "Write your sample chapter — the first chapter of your book, or your strongest chapter if the first isn't representative. 1,500–2,500 words.\n\nThe chapter must:\n- Open with a scene, anecdote, or moment — not background, not throat-clearing, not 'in this chapter I will argue'\n- Make its central argument clear by the end of the first page\n- Use at least one extended scene or case study\n- Have a structural arc: something changes or is revealed by the end\n- End in a way that makes the reader want the next chapter\n\nWrite it as it will appear in the book — finished prose, not a draft.",
        wordCountMin: 1500,
        wordCountMax: 2500,
        tips: [
          "The first line of a book chapter is not a place to warm up. Start with the most interesting thing you have.",
          "Nonfiction chapters need scenes. Facts without scenes are textbooks. Find the human moment that carries your argument.",
          "Your chapter's argument should be clear by page 2 — but don't state it flatly. Let the opening scene imply it, then articulate it.",
          "End with forward momentum. The last line should make the reader feel the pull of the next chapter.",
          "Read it out loud before submitting. You will catch every clunky sentence.",
        ],
        criteria: [
          { name: "Opening strength", description: "The chapter opens with a scene, moment, or image that earns immediate attention — no throat-clearing.", weight: 0.25 },
          { name: "Argument clarity", description: "The chapter's central argument is clear by the end of the first page.", weight: 0.25 },
          { name: "Scene work", description: "At least one extended scene or case study is developed with specific, concrete detail.", weight: 0.20 },
          { name: "Voice", description: "The prose has a consistent, distinct voice — it sounds like one writer with a point of view.", weight: 0.15 },
          { name: "Structural arc", description: "The chapter arrives somewhere — something is revealed, complicated, or resolved by the end.", weight: 0.15 },
        ],
        passThreshold: 68,
      },
    ],
  },
];

export const projects = _allProjects.filter((p) => p.genre !== "fiction");

export function getProject(projectId: string) {
  return projects.find((p) => p.id === projectId) ?? null;
}

export function getPhase(projectId: string, phaseId: string) {
  const project = getProject(projectId);
  return project?.phases.find((ph) => ph.id === phaseId) ?? null;
}
